### ISSUE TITLE
US 1: Browse the entire web in a familiar, conventional, and timely manner so that I can use the system even if I don’t use the filtering feature.

### ISSUE THREAD

**Issue by benbrott** [cjbvt/SpareME#13]

**Comment by cjbvt** [comment]
# Acceptance Criteria
* [ ] Browser doesn’t crash
* [ ] Handles loss of connectivity 
* [ ] Address bar works
  * Search + URLs
* [ ] Back and forward buttons work
  * Everytime you navigate to a new page, the forward button is disabled
  * You can navigate back to pages visited since the launch of the app
* [ ] Refresh button works

**Comment by cjbvt** [comment]
# US 2 Acceptance Criteria
* [ ] Browser loads web pages without breaking any page features (links, videos, etc.)
* [ ] Handles URLs, including malformed URLs (not found page)
* [ ] Scales pages correctly so that websites are displayed properly
* [ ] Make sure web pages load as fast as on a normal browser (Chrome, Firefox)

**Comment by cjbvt** [comment]
# US 3 Acceptance Criteria
* [ ] Native copy/paste works as expected 
* [ ] Can copy text on web pages
* [ ] Can paste text into web page fields
* [ ] Can copy text from address bar
* [ ] Can paste text into address bar
* [ ] Responds properly to tapping vs long pressing

**Comment by cjbvt** [comment]
# US 4 Acceptance Criteria
* [ ] Web pages load without breaking when back/forward button is pressed
* [ ] Correct page is loaded when back is pressed
* [ ] Correct page is loaded when forward is pressed
* [ ] Forward works as expected after back is pressed
* [ ] Forward is disabled when new page is selected
* [ ] Pages load as expected when back/forward button is pressed

**Comment by pg8wood** [comment]
🎉
