### ISSUE TITLE
US 6: Have only hateful text hidden from me so that I can access meaningful content on web pages without seeing hate.

### ISSUE THREAD

**Issue by benbrott** [cjbvt/SpareME#14]

**Comment by cjbvt** [comment]
# Acceptance Criteria
* [ ] Flag similar content until it begins to become blurred
* [ ] Unblur text to determine if it contains hateful text
* [ ] Read entire articles to determine if hateful text was missed
