### ISSUE TITLE
US 15: Login to my account so that I can use my existing personalized filter on another device.

### ISSUE THREAD

**Issue by benbrott** [cjbvt/SpareME#18]

**Comment by cjbvt** [comment]
# Acceptance Criteria
* [ ] Successfully log into correct account
* [ ] Correct account details are retained
* [ ] Correct personalized filter is retained
* [ ] Incorrect credentials are handled
