### ISSUE TITLE
US 7: Flag a chunk of text as “inappropriate” so that it’s immediately hidden from me and similar text is automatically hidden from me in the future.

### ISSUE THREAD

**Issue by cjbvt** [cjbvt/SpareME#36]
# Acceptance Criteria
* [x] Flagging a chunk of text immediately hides the selected text
* [x] Reloading the page shall result in the text being hidden
* [x] The ML model shall respond to an objectively similar chunk of text
